# Source: sample-dadjoke/templates/deployment.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "dadjoke-dev"
  name: "dadjoke-dev"
  namespace: "dev"
spec:
  ports:
   - name: api
     port: 9091
     protocol: "TCP"
     targetPort: 9091
  selector:
    app: "dadjoke-dev"
  sessionAffinity: None
  type: ClusterIP
---
# Source: sample-dadjoke/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    feature: "sample"
    app: "dadjoke-dev"
  name: "dadjoke-dev-v2"
  namespace: "dev"
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 360
  replicas: 1
  selector:
    matchLabels:
      app: "dadjoke-dev"
  strategy:
    
      rollingUpdate:
        maxSurge: "50%"
        maxUnavailable: "50%"
    
  template:
    metadata:
      labels:
        app: "dadjoke-dev"
        version: v2
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9091'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      volumes:
      imagePullSecrets:
      - name: 
      containers:
      - name: "dadjoke-dev"
        volumeMounts:
        image: "uday1bhanu/dadjoke:v2"
        ports:
          - name: api
            containerPort: 9091
        resources:
          limits:
            cpu: ".5"
            memory: "1024Mi"
          requests:
            cpu: ".5"
            memory: "512Mi"
        imagePullPolicy: "Always"
        tty: true
        stdin: true
        envFrom:
        - configMapRef:
            name: internal-service-config
        env:
        - name: JAVA_MAX_MEM_RATIO
          value: "80"
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
    
      
        livenessProbe:
          
          httpGet:
            port: 9091
            path: /actuator/health
            httpHeaders:
          
            - name: Content-Type
              value: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
          
          
          
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 24
      
      
        readinessProbe:
          
          httpGet:
            port: 9091
            path: /actuator/health
            httpHeaders:
          
            - name: Content-Type
              value: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
          
          
          
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 24
---
# Source: sample-dadjoke/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    feature: "sample"
    app: "dadjoke-dev"
  name: "dadjoke-dev-v3"
  namespace: "dev"
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 360
  replicas: 1
  selector:
    matchLabels:
      app: "dadjoke-dev"
  strategy:
    
      rollingUpdate:
        maxSurge: "50%"
        maxUnavailable: "50%"
    
  template:
    metadata:
      labels:
        app: "dadjoke-dev"
        version: v3
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9091'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      volumes:
      imagePullSecrets:
      - name: 
      containers:
      - name: "dadjoke-dev"
        volumeMounts:
        image: "uday1bhanu/dadjoke:v3"
        ports:
          - name: api
            containerPort: 9091
        resources:
          limits:
            cpu: ".5"
            memory: "1024Mi"
          requests:
            cpu: ".5"
            memory: "512Mi"
        imagePullPolicy: "Always"
        tty: true
        stdin: true
        envFrom:
        - configMapRef:
            name: internal-service-config
        env:
        - name: JAVA_MAX_MEM_RATIO
          value: "80"
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
    
      
        livenessProbe:
          
          httpGet:
            port: 9091
            path: /actuator/health
            httpHeaders:
          
            - name: Content-Type
              value: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
          
          
          
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 24
      
      
        readinessProbe:
          
          httpGet:
            port: 9091
            path: /actuator/health
            httpHeaders:
          
            - name: Content-Type
              value: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
          
          
          
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 24